name: Create GitHub Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Issue's title"
        required: true
        type: string
      body:
        description: "Issue's body"
        required: true
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Create a GitHub issue
        uses: peter-evans/create-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.inputs.title }}
          body: ${{ github.event.inputs.body }}
